---
- name: Create vim plugin directory
  file:
    path: "~/.vim/plugin"
    state: directory

- name: Create languagetool directory
  file:
    path: "~/.vim/plugin/languagetool"
    state: directory

- name: Dowload and unarchive language tool 4.0
  unarchive:
    src: https://languagetool.org/download/LanguageTool-stable.zip
    dest: "~/.vim/plugin/languagetool"
    remote_src: yes

- name: Install vim plugins
  command: vim +PlugInstall +qall
