---
- hosts: localhost
  connection: local
  roles:
    - fish
    - python
    - git
    - vim
    - tmux
    - links
    - less
    - ranger
    - network-tools
    - utilities
    - user
    - sudo
    - ssh
