---
- name: Install PulseAudio
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pulseaudio
    - pavucontrol
    - playerctl  # not available for Debian
  when: only_config is not defined
