---
- name: Install NetworkManager and applet
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - networkmanager
    - network-manager-applet
    - networkmanager-openconnect
    - networkmanager-openvpn
  when: only_config is not defined

- name: Enable NetworkManager.service
  become: true
  systemd:
    name: NetworkManager
    enabled: true
  when: ansible_os_family != "NixOS"

