---
- name: Install ranger
  become: true
  package:
    name: ranger
    state: installed
  when: only_config is not defined

- name: Create ranger config directory
  file:
    path: "~/.config/ranger"
    state: directory

- name: Symlink rifle config
  file:
    src: "{{ role_path }}/files/rifle.conf"
    dest: "~/.config/ranger/rifle.conf"
    state: link
