---
- name: Install ranger
  become: true
  package:
    name: ranger
    state: present
  when: only_config is not defined

- name: Symlink ranger config dir
  file:
    src: "{{ role_path }}/files/ranger"
    dest: "~/.config/ranger"
    state: link
