[theme]
name = "slick"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = "xsel -o -b | sed -e 's/\\n//g' | xargs echo -n"
on_click = "xsel -c -b"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}+{swap_used} ({mem_used_percents})"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
on_click="pavucontrol"

[[block]]
block = "net"
format = "{signal_strength} {ip}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{alias} {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 10
alert = 5

[[block]]
block = "disk_space"
path = "/home"
alias = "~"
format = "{alias} {available}"
info_type = "available"
unit = "GB"
interval = 20
warning = 20
alert = 10

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
on_click = "gsimplecal"
