[theme]
theme = "slick"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = "xsel -o -b | sed -e 's/\\n//g' | xargs echo -n"
interval = 1
[[block.click]]
button = "left"
cmd = "xsel -c -b"

[[block]]
block = "memory"
format = "$mem_used+$swap_used ($mem_used_percents)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd ="pavucontrol"

[[block]]
block = "net"
format = "$signal_strength $ip"

[[block]]
block = "battery"
device = "BAT0"

[[block]]
block = "disk_space"
path = "/"
format = "/ $available"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 10
alert = 5

[[block]]
block = "disk_space"
path = "/home"
format = "~ $available"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20
alert = 10

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%a %d.%m %R')"
[[block.click]]
button = "left"
cmd = "gsimplecal"
