#! /usr/bin/env bash

DEFAULT_SINK="$(pacmd list-sinks | egrep -i 'index:' | grep '*' | egrep -o '[0-9]+')"
CURRENT_VOL="$(pactl list sinks | egrep '^[[:space:]]Volume:|^Sink #' | grep -A 1 "Sink #${DEFAULT_SINK}" | grep 'Volume:' | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"

if [ "$CURRENT_VOL" -lt "100" ] ; then
  pactl set-sink-volume $DEFAULT_SINK +${1}%
fi
