---
- include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"

- name: Install i3
  become: true
  package:
    name: "{{ i3_package_name }}"
    state: installed
  when: only_config is not defined

- name: Clone py3status repo
  become: True
  git:
    repo: "https://github.com/JohnAZoidberg/py3status.git"
    version: zoid
    dest: "/opt/.py3status"

- name: Install i3status
  become: True
  package:
    name: i3status
    state: installed
  when: only_config is not defined

- name: Install custom py3status repo
  become: True
  pip:
    chdir: "/opt/.py3status"
    name: "."
    state: present

- name: Symlink i3 config
  file:
    src: "{{ role_path }}/files"
    dest: "~/.i3"
    state: link
    force: true

- name: Install gsimplecal for click on time in py3status
  become: True
  package:
    name: gsimplecal
    state: installed
  when: only_config is not defined

- name: Install python packages for status calendar
  become: true
  pip:
    name: "{{ item }}"
  with_items:
    - pytz
    - tzlocal
  when: only_config is not defined

- name: Install python packages for rss aggregator
  become: true
  pip:
    name: "{{ item }}"
  with_items:
    - requests
  when: only_config is not defined

- name: Symlink wakelock file to lock on suspend and sleep
  become: True
  file:
    src: "{{ role_path }}/files/wakelock.service"
    dest: "/etc/systemd/system/wakelock.service"
    state: link
  when: only_config is not defined

- name: Enable systemd wakelock service
  become: True
  systemd:
    name: wakelock.service
    enabled: True
  when: only_config is not defined

- name: Run i3 on Xorg startup
  become: yes
  lineinfile:
    path: /root/.xinitrc
    line: exec i3
    insertafter: EOF
    create: yes
  when: only_config is not defined
