---
- include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"

- name: Install lightdm
  become: true
  package:
    name:
      - xorg-xinit
      - xorg-server
      - xf86-video-ati
      - xf86-video-amdgpu
      - mesa
      - lib32-mesa
      - vulkan-radeon
      - lib32-vulkan-radeon
      - lightdm
      - lightdm-gtk-greeter
      - alsa-utils
      - zenity
    state: present
  when: only_config is not defined

- name: Enable lightdm
  become: true
  service:
    name: lightdm
    enabled: yes
  when: only_config is not defined

- name: Install i3
  become: true
  package:
    name: "{{ i3_package_name }}"
    state: present
  when: only_config is not defined

- name: Install i3status
  become: True
  package:
    name:
      - i3status
      - i3status-rust
    state: present
  when: only_config is not defined

- name: Symlink i3 config
  file:
    src: "{{ role_path }}/files/i3"
    dest: "~/.i3"
    state: link
    force: true

- name: Install gsimplecal for click on time in py3status
  become: True
  package:
    name: gsimplecal
    state: present
  when: only_config is not defined

- name: Install python packages for status calendar
  become: true
  pip:
    name: [ 'pytz', 'tzlocal' ]
  when: only_config is not defined

- name: Install python packages for rss aggregator
  become: true
  pip:
    name: [ 'requests' ]
  when: only_config is not defined

- name: Symlink wakelock file to lock on suspend and sleep
  become: True
  file:
    src: "{{ role_path }}/files/wakelock.service"
    dest: "/etc/systemd/system/wakelock.service"
    state: link
  when: ansible_os_family != "NixOS"

- name: Enable systemd wakelock service
  become: True
  systemd:
    name: wakelock.service
    enabled: True
  when: only_config is not defined

- name: Symlink xprofile
  file:
    src: "{{ role_path }}/files/.xprofile"
    dest: "~/.xprofile"
    state: link

- name: Run i3 on Xorg startup
  become: yes
  lineinfile:
    path: /root/.xinitrc
    line: exec i3
    insertafter: EOF
    create: yes
  when: only_config is not defined

- name: Create gsimplecal directory
  file:
    path: ~/.config/gsimplecal/
    state: directory

- name: Symlink gsimplecal config
  file:
    src: "{{ role_path }}/files/gsimplecal_config"
    dest: "~/.config/gsimplecal/config"
    state: link

- name: Check if i3_user is defined and fail if not
  fail:
    msg: "Variable i3_user is not defined thus the next set of tasks will fail"
  when: only_config is not defined and i3_user is not defined

- name: Install i3 background change timer
  become: True
  template:
    src: "{{item}}"
    dest: "/etc/systemd/system/{{item}}"
  loop:
    - i3background.timer
    - i3background.service
  when: ansible_os_family != "NixOS" and only_config is not defined and i3_user is defined

- name: Enable Background change timer
  become: True
  systemd:
    name: i3background.timer
    enabled: True
  when: only_config is not defined
