---
- name: Install dunst
  become: True
  package:
    name: dunst
    state: present
  when: only_config is not defined

- name: Create dunst config directory
  file:
    dest: "~/.config/dunst"
    state: directory

- name: Symlink dunst config
  file:
    src: "{{ role_path }}/files/dunstrc"
    dest: "~/.config/dunst/dunstrc"
    state: link
