---
- name: Install dunst
  become: True
  package:
    name: dunst
    state: installed
  when: only_config is not defined

- name: Symlink dunst config
  file:
    src: "{{ role_path }}/files/dunstrc"
    dest: "~/.dunstrc"
    state: link
