---
- name: Install dunst and useful tools
  become: True
  package:
    name:
      - dunst
      - libnotify
      - xfce4-notifyd
    state: present
  when: only_config is not defined

- name: Create dunst config directory
  file:
    dest: "~/.config/dunst"
    state: directory

- name: Symlink dunst config
  file:
    src: "{{ role_path }}/files/dunstrc"
    dest: "~/.config/dunst/dunstrc"
    state: link

- name: Create xfce-notifyd config directory
  file:
    dest: "~/.config/xfce4/xfconf/xfce-perchannel-xml/"
    recurse: yes
    state: directory

- name: Symlink xfce-notifyd config
  file:
    src: "{{ role_path }}/files/xfce4-notifyd.xml"
    dest: "~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml"
    state: link
