let mapleader=","                           " set leader to, (Comma)

" Mapings {{{
noremap <silent> <leader>ev :e $MYVIMRC<cr>  " open .vimrc with <leader>ev
noremap <silent> <leader>sv :so $MYVIMRC<cr>  " open .vimrc with <leader>sv

set mouse=a  " enable mouse control

" Support indenting multiple times in visual mode
vnoremap < <gv
vnoremap > >gv

" move in wrapped line as if they were separate
nnoremap gk k
nnoremap gj j
vnoremap gk k
vnoremap gj j

nnoremap k gk
nnoremap j gj
vnoremap k gk
vnoremap j gj

" scroll 3 lines instead of one
nnoremap <C-Y> 3<C-Y>
nnoremap <C-E> 3<C-E>

" scroll 10 cols instead of one
nnoremap zh 10zh
nnoremap zl 10zl

" Prevent <c-u> from deleting line without undo possibility
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

noremap <leader><space> :nohlsearch<cr><leader><space>     " turn off search highlight
nnoremap <silent><leader>w :%s/\s\+$//<cr>  " delete all trailing whitespace"

nnoremap <F5> :w<cr>:make<cr>                              " at F5 to run make

nnoremap <leader>cwd :lcd %:p:h<cr>:lcd<cr>                 " change working directory to current file
nnoremap <leader>or :browse oldfiles<cr>                    " browse recently used files

" Spell checking
" set spellcapcheck  "[.?!]\_[\])'" \t]\+")                    " checks if the first word of the sentence is big
nnoremap <leader>de :setlocal spell spelllang=de<cr>:set spellcapcheck<cr>       " add Spellcheck for German
nnoremap <leader>en :setlocal spell spelllang=en<cr>:set spellcapcheck<cr>       " add Spellcheck for English
nnoremap <leader>no :set nospell<cr>						" remove spellchecking

if has("win32")

    " Map use of clipboard for easior use on windows
    nnoremap Y "*y
    vnoremap Y "*y
    " Not for P since it has an usefull meaning
endif
" }}}
" Options {{{
" Prevent vim from playing an error sound and flashing the screen
set noerrorbells 	" Only play error bells on error with no error text
set visualbell		" Only flash the screen on such errors
set t_vb=		" Flash screen with no color -> don't flash screen
if has('autocmd')	" Do the above on initialising the GUI because it could be reset by entering the GUI
  autocmd GUIEnter * set visualbell t_vb=
endif

" save as sudo
cmap w!! w !sudo tee > /dev/null %

" save temporary files not in current directory but there
set backupdir=$HOME/.vim/backup//
set directory=$HOME/.vim/tmp//

set encoding=utf-8                          " force utf8 support
syntax on                                   " syntax highlighting
set t_Co=256                                " Use 256 colors
set showmatch                               " highlight matching braces/parentheses/brackets
set cursorline                              " highlight current line
set modelines=1                             " last line of this file applies to just this file
set autoindent
set ruler                                   " show line and column number
set display=lastline,uhex                   " show non printable as hex and long last line
set splitbelow                              " new splits on the right and on the bottom
set splitright                              " more intuitive for LTR languages
set relativenumber                          " show relative line numbers
set number                                  " but absolute of current line
set ignorecase                              " make search case insensitive
set smartcase                               " Case insensitive searches become sensitive with capitals
set hlsearch                                " highlight matches
set shiftwidth=4 tabstop=4 softtabstop=4    " Make a tab only 4 instead of 8 spaces
set expandtab                               " insert spaces when pressing tab
set foldmethod=syntax                       " Make it possible to fold lines with comments
set foldlevel=99 foldlevelstart=99          " open most folds by default

set wildmenu                                " visual autocomplete for command menu
set wildmode=list:full                      " autocomplete first match and show list

" }}}
" Plugins {{{
call plug#begin('~/vimfiles/bundle')

" surround with parentheses, braces, ...
Plug 'tpope/vim-surround'

" repeat advanced plugin commands with .
Plug 'tpope/vim-repeat'

" Automatically insert closing parentheses, brackets, etc.
Plug 'jiangmiao/auto-pairs'


" Snippets
Plug 'SirVer/ultisnips'
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-h>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
" Snippets are separated from the engine
Plug 'honza/vim-snippets'

set runtimepath+=~/dotfiles/vim/snippets/

" klen/python-mode
" scrooloose/syntastic
" Valloric/YouCompleteMe
" matjutsushi/tagbar

Plug 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
let g:Powerline_symbols = 'fanxy'

" show git diff +, -, ~ at the left edge
Plug 'airblade/vim-gitgutter'

call plug#end()
" }}}
" FIle Format dependend {{{
autocmd FileType tex let g:tex_fold_enabled=1
" }}}
" Highlighting and color scheme {{{
" Highlight trailing whitespace when not in insert mode
" and highlight all tabs
highlight EvilTabs ctermbg=red guibg=red
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight EvilTabs ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match EvilTabs /\t/
2match ExtraWhitespace /\s\+\%#\@<!$/

colorscheme solarized  " placed at ~/vimfiles/colors/solarized.vim for windows
set background=light

" Change Spellcheck highlighting to be visible on every console
"hi! link SpellBad ErrorMsg
"hi! link SpellCap Search
highlight SpellBad cterm=underline term=underline ctermbg=Red
highlight SpellCap ctermbg=Red
" }}}

" vim: foldmethod=marker
