#!/usr/bin/env bash
# shamelessly taken from and slightly modified from
# https://github.com/jeroenjanssens/i3-wm-scripts/blob/master/i3-rename-workspace
OLD=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused==true).name')
NEW=$(zenity --text="Enter new name:" --entry --title="Rename workspace $OLD" --entry-text="$OLD")
echo "rename workspace \"$OLD\" to \"$NEW\""
swaymsg "rename workspace \"$OLD\" to \"$NEW\""
