---
- name: Create vimrc directory
  file:
    path: "~/.vim/vimrc.d"
    state: directory

- name: Install solarized colorscheme
  get_url:
    url: https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
    dest: ~/.vim/colors/solarized.vim

- name: Install vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Symlink vimrc.d files
  file:
    src: "{{ role_path }}/files/vimrc.d/{{item}}"
    dest: "~/.vim/vimrc.d/{{item}}"
    state: link
  with_items:
    - plugins.vim
    - spell_check.vim
    - whitespace.vim
    - highlighting.vim
    - c_dev.vim

- name: Install plugins
  command: vim +PlugInstall +qall
