---
- name: Install xfce-terminal
  become: true
  package:
    name: xfce4-terminal
    state: present
  when: only_config is not defined

- name: Ensure xfce4 config dir is present
  file:
    path: "~/.config/xfce4"
    state: directory

- name: Symlink xfce4-terminal config
  file:
    src: "{{ role_path }}/files"
    dest: "~/.config/xfce4/terminal"
    state: link
