---
- name: Install tmux
  become: true
  package:
    name: tmux
    state: installed
  when: only_config is not defined

- name: Symlink config
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"
    state: link
