---
- name: Install xcape
  become: true
  package:
    name: xcape
    state: present

- name: Symlink xcape fish config file
  file:
    src: "{{ role_path }}/files/xcape.config"
    dest: "~/.config/fish/xcape.config"
    state: link
