---
- include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"

- name: Install utilities
  become: true
  package:
    name: "{{ item }}"
  with_items:
    - unzip
    - wget
    - "{{ openssh_package_name }}"
