---
- include_vars: "{{ item }}"
  with_first_found:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"

- name: Install vim
  become: true
  package:
    name: "{{ vim_package_name }}"
    state: present
  when: only_config is not defined

- name: Set vim as default editor (Debian)
  become: true
  command: "update-alternatives --set editor /usr/bin/vim.nox"
  when: ansible_os_family == "Debian"

- name: Set vim as default editor (global env)
  become: true
  lineinfile:
    path: /etc/environment
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.val }}"
    create: yes
    mode: 644
    owner: root
    group: root
  when: ansible_os_family != "NixOS"
  with_items:
    - { "key": "EDITOR", "val": "vim" }
    - { "key": "VISUAL", "val": "vim" }

- name: Create directories for backup and temporary files
  file:
    path: "~/.vim/{{ item }}"
    state: directory
  with_items:
    - tmp
    - backup
    - autoload
    - colors

- name: Symlink vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "~/.vimrc"
    state: link
