# pip install neovim
# apt install npm
- name: Install neovim and dependencies
  become: true
  package:
    name:
      - neovim
      - python-pynvim
    state: present
  when: only_config is not defined

- name: Create directories for neovim config
  file:
    path: "~/.config/nvim/"
    state: directory

- name: Delete old init.vim
  file:
    dest: "~/.config/nvim/init.vim"
    state: absent

- name: Symlink init.lua
  file:
    src: "{{ role_path }}/files/init.lua"
    dest: "~/.config/nvim/init.lua"
    state: link
