---
- name: Install xbacklight and intel driver to control backlight
  become: true
  package:
    name: "{{ item }}"
    state: present
  when: only_config is not defined
  with_items:
    - xorg-xbacklight
    - xf86-video-intel
